### ISSUE TITLE
Cannot find module 'use-debounce'

### ISSUE THREAD

**Issue by denchen** [xnimorz/use-debounce#151]
**Describe the bug**
With the just-released 9.0.0, can't import anything from this library.

**To Reproduce**
```javascript
import { useThrottledCallback } from 'use-debounce';
```

The problem only manifests itself when I'm using Jest.

I believe this is a problem with `exports` in `package.json`:
```
  "exports": {
    ".": {
      "node": {
        "types": "./dist/index.d.ts",
        "module": "./dist/index.module.js",
        "require": "./dist/index.js",
        "import": "./dist/index.mjs"
      },
      "browser": {
        "types": "./dist/index.d.ts",
        "import": "./dist/index.module.js",
        "require": "./dist/index.js"
      },
      "default": "./dist/index.module.js"
    },
    "./package.json": "./package.json"
  },
```

But the files included are:
```
% ls node_modules/use-debounce/dist/
index.cjs                  index.modern.js            index.umd.js               useThrottledCallback.d.ts
index.cjs.map              index.modern.js.map        index.umd.js.map
index.d.ts                 index.module.js            useDebounce.d.ts
index.mjs                  index.module.js.map        useDebouncedCallback.d.ts
```

The module for `"require"` is not there.

**Comment by xnimorz** [comment]
Hey @denchen !

Sorry for the inconvenience. I've just published v9.0.1 it should fix the issue

**Comment by denchen** [comment]
Hi @xnimorz ,

So the import problem is fixed, but now I'm getting a new error, again within Jest:

```
  ● App › should have error state

    TypeError: (0 , _useDebounce.useThrottledCallback) is not a function

      45 |
    > 46 |   const throttledScroll = useThrottledCallback(
         |                                               ^

```

My actual app works just fine with `useThrottledCallback()`. It's just failing within the tests.

**Comment by malfianrasyidin** [comment]
Hey @xnimorz, thanks for the quick fix for the `v9.0.1`, but it seems it has not resolved the issue of importing the `useDebounce` as below:

![image](https://user-images.githubusercontent.com/25271386/204511674-7847c1c4-e062-4eb9-8be1-926859da9a68.png)

It works fine for the `v8.0.4`, but not the latest major version. 

![image](https://user-images.githubusercontent.com/25271386/204512025-5617c400-02c3-4542-8417-643d55d3afdb.png)


Would you mind checking it or advising me, please? Thank you!

**Comment by xnimorz** [comment]
Hey @malfianrasyidin 
I’ll take care of it later today. 

I’d advise using 8.0.4 for now.

**Comment by xnimorz** [comment]
Okay, So I've reverted recent 9.0.0 changes, and it should be back to normal.

**Comment by denchen** [comment]
Thanks @xnimorz . I've verified that everything is working again, both app and tests, at least in my setup.
